source 'https://github.com/CocoaPods/Specs.git'

target 'MWPhotoBrowser_Example', :exclusive => true do
  pod "MWPhotoBrowser", :path => "../"
  pod 'pop'
end

target 'MWPhotoBrowser_Tests', :exclusive => true do
  pod "MWPhotoBrowser", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
